[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spandas"
version = "0.1.0"
description = "Enhanced pandas-like interface for PySpark"
authors = [{name = "Zeusu Sato", email = "zeusu.sato@dorodango.biz"}]
urls = {"Homepage" = "https://github.com/zeusu-sato/spandas"}
requires-python = ">=3.7"
dependencies = [
    "pandas>=1.5,<2.0",
    "numpy>=1.22,<2.0",
    "pyarrow>=8,<13",
    "matplotlib>=3.7,<3.8",
    "swifter>=1.4,<1.5",
    "dask[dataframe]>=2024.2,<2024.7",
    "dask-expr>=1.0,<1.1",
]
