name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -U ".[dev]" .
      - run: pip check
      - run: pytest -q
      - run: |
          python - <<'PY'
          import spandas, pandas as pd, importlib.util as iu
          assert iu.find_spec("spandas")
          print("OK", spandas.__version__, pd.__version__)
          PY
  dask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -U ".[dev]" .
      - run: pip install -U ".[dask_legacy]"
      - run: pip check
      - run: pytest -q -m "dask"
