name: CI
on: [push, pull_request]

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install -U pip
      - run: pip install -U .
      - run: pytest -q

  optional-extras:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - extra: dask_legacy
            install: ".[dask_legacy]"
            pytest-args: "-m 'dask'"
            env: {}
          - extra: spark
            install: ".[spark]"
            pytest-args: "-m 'spark'"
            env:
              SPANDAS_ENABLE_SPARK_TESTS: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -U .
      - run: pip install -U "${{ matrix.install }}"
      - run: pytest -q ${{ matrix.pytest-args }}
        env: ${{ matrix.env }}
