name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - name: Install base (constrained)
        run: pip install -U -c constraints.txt .
      - name: Install extras (unconstrained)
        run: pip install -U ".[local]" ".[dask_legacy]"
      - run: pip check
      - name: Run tests
        run: pytest -q
