name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -c constraints.txt .[local]
      - run: python -m pip install -U pytest pytest-cov
      - run: pip check
      - run: |
          python - <<'PY'
          import spandas, pandas as pd, importlib.util as iu
          assert iu.find_spec("spandas")
          print("OK", spandas.__version__, pd.__version__)
          PY
