name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m pip install -U pip
      - run: pip install -U -c constraints.txt .[dev]
      - name: sentinel
        run: |
          pip freeze | grep -Ei '^(dask|dask-expr|swifter)=' && exit 1 || true
          ! git grep -nE '(^|[^a-zA-Z])(dask|dask_expr|swifter)\b' -- ':!docs/' ':!.github/workflows/' || (echo "forbidden import" && exit 1)
      - run: pytest -q
